# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.CharField(max_length=200, verbose_name='内容')),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
    ]
