# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='电影名')),
                ('img', models.CharField(max_length=100, verbose_name='电影海报')),
                ('filename', models.CharField(max_length=50, verbose_name='电影文件名')),
                ('typefile', models.CharField(max_length=50, verbose_name='所属类别')),
                ('timelong', models.IntegerField(verbose_name='电影时长')),
                ('filelong', models.IntegerField(verbose_name='电影大小')),
                ('filehd', models.CharField(max_length=10, verbose_name='高清类别')),
                ('description', models.CharField(max_length=200, verbose_name='电影简介')),
                ('director', models.CharField(max_length=10, verbose_name='导演')),
                ('actors', models.CharField(max_length=100, verbose_name='主要演员')),
                ('language', models.CharField(max_length=10, verbose_name='电影语言')),
                ('issrt', models.CharField(max_length=10, verbose_name='是否字幕')),
                ('startyear', models.CharField(max_length=10, verbose_name='上映年份')),
                ('star', models.IntegerField(verbose_name='豆瓣评分')),
                ('pub_date', models.DateTimeField(verbose_name='记录时间')),
            ],
        ),
    ]
