# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u540d')),
                ('img', models.CharField(max_length=100, verbose_name='\u7535\u5f71\u6d77\u62a5')),
                ('videopath', models.CharField(max_length=200, verbose_name='\u7535\u5f71\u8def\u5f84')),
                ('filehd', models.IntegerField(choices=[(0, b'1080P'), (1, b'720P'), (2, b'720P/1080P')], default=0, verbose_name='\u9ad8\u6e05\u7c7b\u522b')),
                ('description', models.TextField(verbose_name='\u7535\u5f71\u7b80\u4ecb')),
                ('director', models.CharField(max_length=10, verbose_name='\u5bfc\u6f14')),
                ('actors', models.TextField(verbose_name='\u4e3b\u8981\u6f14\u5458')),
                ('language', models.IntegerField(choices=[(0, b'\xe5\x9b\xbd\xe8\xaf\xad'), (1, b'\xe5\xa4\x96\xe8\xaf\xad')], default=0, verbose_name='\u7535\u5f71\u8bed\u8a00')),
                ('issrt', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=0, verbose_name='\u662f\u5426\u5b57\u5e55')),
                ('startyear', models.CharField(max_length=10, verbose_name='\u4e0a\u6620\u5e74\u4efd')),
                ('star', models.IntegerField(default=0, verbose_name='\u8c46\u74e3\u8bc4\u5206')),
                ('xl720_id', models.IntegerField(default=0, verbose_name='\u8fc5\u96f7ID')),
                ('db_id', models.IntegerField(default=0, verbose_name='\u8c46\u74e3ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u8bb0\u5f55\u65f6\u95f4')),
            ],
        ),
    ]
