# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='电影简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
    ]
