# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='filehd',
            field=models.CharField(choices=[(0, '1080P'), (1, '720P'), (2, '720P/1080P')], default=0, max_length=10, verbose_name='高清类别'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='issrt',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否字幕'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[(0, '国语'), (1, '外语')], default=0, max_length=10, verbose_name='电影语言'),
        ),
    ]
