# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20190624_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mvarea',
            field=models.IntegerField(choices=[(0, '中国/内地'), (1, '中国/香港'), (2, '美国'), (3, '欧洲'), (4, '日韩'), (5, '印度'), (6, '其他')], default=0, verbose_name='发行地区'),
        ),
        migrations.AddField(
            model_name='movie',
            name='mvtype',
            field=models.IntegerField(choices=[(0, '动作片'), (1, '科幻片'), (2, '喜剧片'), (3, '恐怖片'), (4, '悬疑片'), (5, '动画片'), (6, '纪录片')], default=0, verbose_name='电影类型'),
        ),
    ]
