# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20190624_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_mv',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否电影'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mvtype',
            field=models.IntegerField(choices=[(0, '动作片'), (1, '科幻片'), (2, '喜剧片'), (3, '恐怖片'), (4, '悬疑片'), (5, '剧情片'), (6, '动画片'), (7, '纪录片')], default=0, verbose_name='电影类型'),
        ),
    ]
